# Generated by Django 5.1.7 on 2025-04-05 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='provider',
        ),
    ]
