# Generated by Django 5.1.7 on 2025-04-07 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.booking'),
        ),
        migrations.AddField(
            model_name='notification',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.servicereview'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking_created', 'New Booking'), ('booking_updated', 'Booking Update'), ('review_created', 'New Review'), ('system', 'System Notification'), ('promotion', 'Promotional')], max_length=20),
        ),
    ]
