# Generated by Django 5.1.7 on 2025-04-01 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='is_verified',
        ),
    ]
